//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3649
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.Receiver {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptionType", Namespace="http://tempuri.org/")]
    public enum EncryptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AES = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DES = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenSSL = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Receiver.ReceiveServiceSoap")]
    public interface ReceiveServiceSoap {
        
        // CODEGEN: Generating message contract since element name authenticationTokenXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/authenticateSender", ReplyAction="*")]
        ClientApplication.Receiver.authenticateSenderResponse authenticateSender(ClientApplication.Receiver.authenticateSenderRequest request);
        
        // CODEGEN: Generating message contract since element name dataXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificationAndAlive", ReplyAction="*")]
        ClientApplication.Receiver.VerificationAndAliveResponse VerificationAndAlive(ClientApplication.Receiver.VerificationAndAliveRequest request);
        
        // CODEGEN: Generating message contract since element name sender_userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNonceForAuthentication", ReplyAction="*")]
        ClientApplication.Receiver.GetNonceForAuthenticationResponse GetNonceForAuthentication(ClientApplication.Receiver.GetNonceForAuthenticationRequest request);
        
        // CODEGEN: Generating message contract since element name authenticationTokenXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/authenticateSenderFixed", ReplyAction="*")]
        ClientApplication.Receiver.authenticateSenderFixedResponse authenticateSenderFixed(ClientApplication.Receiver.authenticateSenderFixedRequest request);
        
        // CODEGEN: Generating message contract since element name dataXML from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificationAndAliveFixed", ReplyAction="*")]
        ClientApplication.Receiver.VerificationAndAliveFixedResponse VerificationAndAliveFixed(ClientApplication.Receiver.VerificationAndAliveFixedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateSenderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateSender", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.authenticateSenderRequestBody Body;
        
        public authenticateSenderRequest() {
        }
        
        public authenticateSenderRequest(ClientApplication.Receiver.authenticateSenderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authenticateSenderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationTokenXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ClientApplication.Receiver.EncryptionType enc_type;
        
        public authenticateSenderRequestBody() {
        }
        
        public authenticateSenderRequestBody(string authenticationTokenXML, ClientApplication.Receiver.EncryptionType enc_type) {
            this.authenticationTokenXML = authenticationTokenXML;
            this.enc_type = enc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateSenderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateSenderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.authenticateSenderResponseBody Body;
        
        public authenticateSenderResponse() {
        }
        
        public authenticateSenderResponse(ClientApplication.Receiver.authenticateSenderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authenticateSenderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticateSenderResult;
        
        public authenticateSenderResponseBody() {
        }
        
        public authenticateSenderResponseBody(string authenticateSenderResult) {
            this.authenticateSenderResult = authenticateSenderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationAndAliveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificationAndAlive", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.VerificationAndAliveRequestBody Body;
        
        public VerificationAndAliveRequest() {
        }
        
        public VerificationAndAliveRequest(ClientApplication.Receiver.VerificationAndAliveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificationAndAliveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ClientApplication.Receiver.EncryptionType enc_type;
        
        public VerificationAndAliveRequestBody() {
        }
        
        public VerificationAndAliveRequestBody(string dataXML, ClientApplication.Receiver.EncryptionType enc_type) {
            this.dataXML = dataXML;
            this.enc_type = enc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationAndAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificationAndAliveResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.VerificationAndAliveResponseBody Body;
        
        public VerificationAndAliveResponse() {
        }
        
        public VerificationAndAliveResponse(ClientApplication.Receiver.VerificationAndAliveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificationAndAliveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificationAndAliveResult;
        
        public VerificationAndAliveResponseBody() {
        }
        
        public VerificationAndAliveResponseBody(string VerificationAndAliveResult) {
            this.VerificationAndAliveResult = VerificationAndAliveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNonceForAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNonceForAuthentication", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.GetNonceForAuthenticationRequestBody Body;
        
        public GetNonceForAuthenticationRequest() {
        }
        
        public GetNonceForAuthenticationRequest(ClientApplication.Receiver.GetNonceForAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNonceForAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sender_userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ClientApplication.Receiver.EncryptionType enc_type;
        
        public GetNonceForAuthenticationRequestBody() {
        }
        
        public GetNonceForAuthenticationRequestBody(string sender_userName, ClientApplication.Receiver.EncryptionType enc_type) {
            this.sender_userName = sender_userName;
            this.enc_type = enc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNonceForAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNonceForAuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.GetNonceForAuthenticationResponseBody Body;
        
        public GetNonceForAuthenticationResponse() {
        }
        
        public GetNonceForAuthenticationResponse(ClientApplication.Receiver.GetNonceForAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNonceForAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNonceForAuthenticationResult;
        
        public GetNonceForAuthenticationResponseBody() {
        }
        
        public GetNonceForAuthenticationResponseBody(string GetNonceForAuthenticationResult) {
            this.GetNonceForAuthenticationResult = GetNonceForAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateSenderFixedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateSenderFixed", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.authenticateSenderFixedRequestBody Body;
        
        public authenticateSenderFixedRequest() {
        }
        
        public authenticateSenderFixedRequest(ClientApplication.Receiver.authenticateSenderFixedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authenticateSenderFixedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticationTokenXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ClientApplication.Receiver.EncryptionType enc_type;
        
        public authenticateSenderFixedRequestBody() {
        }
        
        public authenticateSenderFixedRequestBody(string authenticationTokenXML, ClientApplication.Receiver.EncryptionType enc_type) {
            this.authenticationTokenXML = authenticationTokenXML;
            this.enc_type = enc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateSenderFixedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateSenderFixedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.authenticateSenderFixedResponseBody Body;
        
        public authenticateSenderFixedResponse() {
        }
        
        public authenticateSenderFixedResponse(ClientApplication.Receiver.authenticateSenderFixedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class authenticateSenderFixedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authenticateSenderFixedResult;
        
        public authenticateSenderFixedResponseBody() {
        }
        
        public authenticateSenderFixedResponseBody(string authenticateSenderFixedResult) {
            this.authenticateSenderFixedResult = authenticateSenderFixedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationAndAliveFixedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificationAndAliveFixed", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.VerificationAndAliveFixedRequestBody Body;
        
        public VerificationAndAliveFixedRequest() {
        }
        
        public VerificationAndAliveFixedRequest(ClientApplication.Receiver.VerificationAndAliveFixedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificationAndAliveFixedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataXML;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ClientApplication.Receiver.EncryptionType enc_type;
        
        public VerificationAndAliveFixedRequestBody() {
        }
        
        public VerificationAndAliveFixedRequestBody(string dataXML, ClientApplication.Receiver.EncryptionType enc_type) {
            this.dataXML = dataXML;
            this.enc_type = enc_type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificationAndAliveFixedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificationAndAliveFixedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplication.Receiver.VerificationAndAliveFixedResponseBody Body;
        
        public VerificationAndAliveFixedResponse() {
        }
        
        public VerificationAndAliveFixedResponse(ClientApplication.Receiver.VerificationAndAliveFixedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificationAndAliveFixedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificationAndAliveFixedResult;
        
        public VerificationAndAliveFixedResponseBody() {
        }
        
        public VerificationAndAliveFixedResponseBody(string VerificationAndAliveFixedResult) {
            this.VerificationAndAliveFixedResult = VerificationAndAliveFixedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ReceiveServiceSoapChannel : ClientApplication.Receiver.ReceiveServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReceiveServiceSoapClient : System.ServiceModel.ClientBase<ClientApplication.Receiver.ReceiveServiceSoap>, ClientApplication.Receiver.ReceiveServiceSoap {
        
        public ReceiveServiceSoapClient() {
        }
        
        public ReceiveServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiveServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiveServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.Receiver.authenticateSenderResponse ClientApplication.Receiver.ReceiveServiceSoap.authenticateSender(ClientApplication.Receiver.authenticateSenderRequest request) {
            return base.Channel.authenticateSender(request);
        }
        
        public string authenticateSender(string authenticationTokenXML, ClientApplication.Receiver.EncryptionType enc_type) {
            ClientApplication.Receiver.authenticateSenderRequest inValue = new ClientApplication.Receiver.authenticateSenderRequest();
            inValue.Body = new ClientApplication.Receiver.authenticateSenderRequestBody();
            inValue.Body.authenticationTokenXML = authenticationTokenXML;
            inValue.Body.enc_type = enc_type;
            ClientApplication.Receiver.authenticateSenderResponse retVal = ((ClientApplication.Receiver.ReceiveServiceSoap)(this)).authenticateSender(inValue);
            return retVal.Body.authenticateSenderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.Receiver.VerificationAndAliveResponse ClientApplication.Receiver.ReceiveServiceSoap.VerificationAndAlive(ClientApplication.Receiver.VerificationAndAliveRequest request) {
            return base.Channel.VerificationAndAlive(request);
        }
        
        public string VerificationAndAlive(string dataXML, ClientApplication.Receiver.EncryptionType enc_type) {
            ClientApplication.Receiver.VerificationAndAliveRequest inValue = new ClientApplication.Receiver.VerificationAndAliveRequest();
            inValue.Body = new ClientApplication.Receiver.VerificationAndAliveRequestBody();
            inValue.Body.dataXML = dataXML;
            inValue.Body.enc_type = enc_type;
            ClientApplication.Receiver.VerificationAndAliveResponse retVal = ((ClientApplication.Receiver.ReceiveServiceSoap)(this)).VerificationAndAlive(inValue);
            return retVal.Body.VerificationAndAliveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.Receiver.GetNonceForAuthenticationResponse ClientApplication.Receiver.ReceiveServiceSoap.GetNonceForAuthentication(ClientApplication.Receiver.GetNonceForAuthenticationRequest request) {
            return base.Channel.GetNonceForAuthentication(request);
        }
        
        public string GetNonceForAuthentication(string sender_userName, ClientApplication.Receiver.EncryptionType enc_type) {
            ClientApplication.Receiver.GetNonceForAuthenticationRequest inValue = new ClientApplication.Receiver.GetNonceForAuthenticationRequest();
            inValue.Body = new ClientApplication.Receiver.GetNonceForAuthenticationRequestBody();
            inValue.Body.sender_userName = sender_userName;
            inValue.Body.enc_type = enc_type;
            ClientApplication.Receiver.GetNonceForAuthenticationResponse retVal = ((ClientApplication.Receiver.ReceiveServiceSoap)(this)).GetNonceForAuthentication(inValue);
            return retVal.Body.GetNonceForAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.Receiver.authenticateSenderFixedResponse ClientApplication.Receiver.ReceiveServiceSoap.authenticateSenderFixed(ClientApplication.Receiver.authenticateSenderFixedRequest request) {
            return base.Channel.authenticateSenderFixed(request);
        }
        
        public string authenticateSenderFixed(string authenticationTokenXML, ClientApplication.Receiver.EncryptionType enc_type) {
            ClientApplication.Receiver.authenticateSenderFixedRequest inValue = new ClientApplication.Receiver.authenticateSenderFixedRequest();
            inValue.Body = new ClientApplication.Receiver.authenticateSenderFixedRequestBody();
            inValue.Body.authenticationTokenXML = authenticationTokenXML;
            inValue.Body.enc_type = enc_type;
            ClientApplication.Receiver.authenticateSenderFixedResponse retVal = ((ClientApplication.Receiver.ReceiveServiceSoap)(this)).authenticateSenderFixed(inValue);
            return retVal.Body.authenticateSenderFixedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplication.Receiver.VerificationAndAliveFixedResponse ClientApplication.Receiver.ReceiveServiceSoap.VerificationAndAliveFixed(ClientApplication.Receiver.VerificationAndAliveFixedRequest request) {
            return base.Channel.VerificationAndAliveFixed(request);
        }
        
        public string VerificationAndAliveFixed(string dataXML, ClientApplication.Receiver.EncryptionType enc_type) {
            ClientApplication.Receiver.VerificationAndAliveFixedRequest inValue = new ClientApplication.Receiver.VerificationAndAliveFixedRequest();
            inValue.Body = new ClientApplication.Receiver.VerificationAndAliveFixedRequestBody();
            inValue.Body.dataXML = dataXML;
            inValue.Body.enc_type = enc_type;
            ClientApplication.Receiver.VerificationAndAliveFixedResponse retVal = ((ClientApplication.Receiver.ReceiveServiceSoap)(this)).VerificationAndAliveFixed(inValue);
            return retVal.Body.VerificationAndAliveFixedResult;
        }
    }
}
